language: node_js
node_js:
  - '14.16.1'
script:
  - set -e

  - echo 'Installing...' && echo -en 'travis_fold:start:install\\r'
  - node common/scripts/install-run-rush.js install
  - echo -en 'travis_fold:end:install\\r'

  - echo 'Building...' && echo -en 'travis_fold:start:build\\r'
  - node common/scripts/install-run-rush.js rebuild --verbose
  - echo -en 'travis_fold:end:build\\r'

  - echo 'Publishing...'
  - node common/scripts/install-run-rush.js version --bump 
  - echo 'Publishing Done..'
